// $Id: sdconfig.h,v 1.1 2006/03/06 12:59:08 fumi Exp $

#ifndef SDCONFIG_H
#define SDCONFIG_H

#define HOST_IS_LITTLE_ENDIAN
#define FAIL_NOT_ALIGNED_ADDRESS

#define OPTION_DEFAULT_AFTER_IMAGE true
#define OPTION_DEFAULT_ANTI_ALIAS  true
#define OPTION_DEFAULT_EXPANTION   2

#endif
