winsound.o: sound/winsound.cpp include/winsound.h \
  ../common/include/sdsound.h ../common/include/sound.h
winlcdfont.o: font/winlcdfont.cpp include/winlcdfont.h \
  ../common/include/sdlcdfont.h ../common/include/sdlcdfont.h \
  ../common/include/cmlcd.h
winlcdfontaa.o: font/winlcdfontaa.cpp include/winlcdfont.h \
  ../common/include/sdlcdfont.h ../common/include/sdlcdfont.h \
  ../common/include/cmlcd.h
winlcdfontsjis.o: font/winlcdfontsjis.cpp include/winlcdfont.h \
  ../common/include/sdlcdfont.h ../common/include/sdlcdfont.h \
  ../common/include/cmlcd.h ../common/include/cessjis.h
winlcdfontaasjis.o: font/winlcdfontaasjis.cpp include/winlcdfont.h \
  ../common/include/sdlcdfont.h ../common/include/sdlcdfont.h \
  ../common/include/cmlcd.h ../common/include/cessjis.h
winfindfile.o: findfile/winfindfile.cpp include/winfindfile.h \
  ../common/include/sdfindfile.h
winlcdfactory.o: graphic/winlcdfactory.cpp include/winlcd.h \
  ../common/include/sdlcd.h include/winlcdfactory.h \
  ../widgetlib/include/sdlcdfactory.h ../common/include/cmlcd.h
winlcd.o: graphic/winlcd.cpp include/winlcd.h ../common/include/sdlcd.h \
  include/winlcdfont.h ../common/include/sdlcdfont.h \
  ../common/include/cmlcd.h ../common/include/cmlcdfunc.h \
  ../common/include/cmlcd.h
winlcdflip.o: graphic/winlcdflip.cpp include/winlcd.h \
  ../common/include/sdlcd.h ../common/include/cmlcd.h \
  ../common/include/cmlcdfunc.h ../common/include/cmlcd.h
winlcd102x64.o: graphic/winlcd102x64.cpp include/winlcd.h \
  ../common/include/sdlcd.h ../common/include/cmlcd.h \
  ../common/include/cmlcdfunc.h ../common/include/cmlcd.h \
  ../common/include/rupaddress.h ../common/include/address.h \
  ../common/include/memory.h
winlogoutputevent.o: log/winlogoutputevent.cpp \
  include/winlogoutputevent.h ../common/include/logoutput.h
winoption.o: option/winoption.cpp ../common/include/option.h \
  ../common/include/optionlist.h ../common/include/optionitem.h \
  include/winoption.h ../widgetlib/include/widgetoption.h \
  ../common/include/option.h
winpropwindow.o: option/winpropwindow.cpp include/winpropwindow.h \
  include/winpropwindowlog.h include/winoption.h \
  ../widgetlib/include/widgetoption.h ../common/include/option.h \
  ../common/include/optionlist.h include/winresource.h \
  ../common/include/log.h
winpropwindowlog.o: option/winpropwindowlog.cpp include/winresource.h \
  include/winpropwindowlog.h
