$(TARGET_DIR)/sdlcdfactory.o: ./lcd/sdlcdfactory.cpp include/sdlcdfactory.h \
  ../common/include/option.h ../common/include/optionlist.h \
  ../common/include/optionitem.h ../common/include/ruputer.h \
  ../common/include/exffile.h ../common/include/throwable.h \
  ../common/include/state.h include/widgetoption.h \
  ../common/include/option.h
	$(CXX) $(CXXFLAGS) -o $@ -c $<
$(TARGET_DIR)/widgetoption.o: ./option/widgetoption.cpp include/widgetconfig.h \
  ../common/include/option.h ../common/include/optionlist.h \
  ../common/include/optionitem.h include/widgetoption.h \
  ../common/include/option.h
	$(CXX) $(CXXFLAGS) -o $@ -c $<
