// $Id: language.h,v 1.2 2006/01/04 13:47:45 fumi Exp $

#define LANGUAGE_TEST 0

#if LANGUAGE_TEST == 0
# define LANGUAGE_JAPANESE LANGUAGE LANG_JAPANESE, SUBLANG_DEFAULT
# define LANGUAGE_ENGLISH LANGUAGE LANG_ENGLISH, SUBLANG_DEFAULT
#else
# define LANGUAGE_ENGLISH LANGUAGE LANG_JAPANESE, SUBLANG_DEFAULT
# define LANGUAGE_JAPANESE LANGUAGE LANG_ENGLISH, SUBLANG_DEFAULT
#endif
